steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'backend/Dockerfile.avatar', '-t', 'gcr.io/$PROJECT_ID/avatar-backend', '.']
images:
  - 'gcr.io/$PROJECT_ID/avatar-backend'


