// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// These are PUBLIC client-side configuration keys that are safe to include
/// in the client application. They are different from server-side API keys
/// which should be kept in environment variables.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _apiKey() {
    // Robust: kein Crash, wenn dotenv nicht geladen ist
    try {
      if (dotenv.isInitialized) {
        final v = dotenv.env['FIREBASE_WEB_API_KEY'];
        if (v != null && v.isNotEmpty) return v;
      }
    } catch (_) {}
    const fromEnv = String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: '',
    );
    return fromEnv; // kann leer sein – App startet trotzdem
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _apiKey(),
    appId: '1:590744030274:web:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    authDomain: 'sunriza26.firebaseapp.com',
    storageBucket: 'sunriza26.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _apiKey(),
    appId: '1:590744030274:android:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    storageBucket: 'sunriza26.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _apiKey(),
    appId: '1:590744030274:ios:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    storageBucket: 'sunriza26.firebasestorage.app',
    iosBundleId: 'com.example.sunriza26',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _apiKey(),
    appId: '1:590744030274:ios:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    storageBucket: 'sunriza26.firebasestorage.app',
    iosBundleId: 'com.example.sunriza26',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _apiKey(),
    appId: '1:590744030274:web:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    authDomain: 'sunriza26.firebaseapp.com',
    storageBucket: 'sunriza26.firebasestorage.app',
  );
}
