// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzgTKSf4yBpGd9udWlCsw6MdtoE2Tynxs',
    appId: '1:590744030274:web:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    authDomain: 'sunriza26.firebaseapp.com',
    storageBucket: 'sunriza26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzgTKSf4yBpGd9udWlCsw6MdtoE2Tynxs',
    appId: '1:590744030274:android:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    storageBucket: 'sunriza26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzgTKSf4yBpGd9udWlCsw6MdtoE2Tynxs',
    appId: '1:590744030274:ios:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    storageBucket: 'sunriza26.firebasestorage.app',
    iosBundleId: 'com.example.sunriza26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzgTKSf4yBpGd9udWlCsw6MdtoE2Tynxs',
    appId: '1:590744030274:ios:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    storageBucket: 'sunriza26.firebasestorage.app',
    iosBundleId: 'com.example.sunriza26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzgTKSf4yBpGd9udWlCsw6MdtoE2Tynxs',
    appId: '1:590744030274:web:d2dcc5434d73cb483b31db',
    messagingSenderId: '590744030274',
    projectId: 'sunriza26',
    authDomain: 'sunriza26.firebaseapp.com',
    storageBucket: 'sunriza26.firebasestorage.app',
  );
}
