// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_hauau_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1zmQxsXRgGT0HvCxjYFIZoEggnXji7Gc',
    appId: '1:676848888036:web:14abd5d64e8a2c971d24f1',
    messagingSenderId: '676848888036',
    projectId: 'hauau-prod',
    authDomain: 'hauau-prod.firebaseapp.com',
    storageBucket: 'hauau-prod.firebasestorage.app',
    measurementId: 'G-HH172B3QXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2aR5p-xZ1wIUK5gHbAH32g6_BQWa2rCk',
    appId: '1:676848888036:android:1c0f3ad0ca16519e1d24f1',
    messagingSenderId: '676848888036',
    projectId: 'hauau-prod',
    storageBucket: 'hauau-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbuRa6jMj6o7xdPrbsy51ng2IP5RTx7lc',
    appId: '1:676848888036:ios:86db61f72f74cfe81d24f1',
    messagingSenderId: '676848888036',
    projectId: 'hauau-prod',
    storageBucket: 'hauau-prod.firebasestorage.app',
    iosBundleId: 'de.hauau.hauauapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbuRa6jMj6o7xdPrbsy51ng2IP5RTx7lc',
    appId: '1:676848888036:ios:ec01eefa94b078d21d24f1',
    messagingSenderId: '676848888036',
    projectId: 'hauau-prod',
    storageBucket: 'hauau-prod.firebasestorage.app',
    iosBundleId: 'com.example.sunriza26',
  );
}
