// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRdAKnkLN4P_O3ahbHEUz1Z6QPa51ZPU',
    appId: '1:198085957474:web:4e496bdac31e4a5f9ffe3b',
    messagingSenderId: '198085957474',
    projectId: 'hauau-dev',
    authDomain: 'hauau-dev.firebaseapp.com',
    storageBucket: 'hauau-dev.firebasestorage.app',
    measurementId: 'G-FBBT9D49YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxsCCoqrTPn3zutnueeo4v7A6qf6kP-bc',
    appId: '1:198085957474:android:dca198229407239f9ffe3b',
    messagingSenderId: '198085957474',
    projectId: 'hauau-dev',
    storageBucket: 'hauau-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWs518yC94CZf86OYXFYxrVStuAe_ZEy8',
    appId: '1:198085957474:ios:baf6cc6dbadf8b7b9ffe3b',
    messagingSenderId: '198085957474',
    projectId: 'hauau-dev',
    storageBucket: 'hauau-dev.firebasestorage.app',
    iosBundleId: 'de.hauau.hauauapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWs518yC94CZf86OYXFYxrVStuAe_ZEy8',
    appId: '1:198085957474:ios:c4815466d46d58f39ffe3b',
    messagingSenderId: '198085957474',
    projectId: 'hauau-dev',
    storageBucket: 'hauau-dev.firebasestorage.app',
    iosBundleId: 'com.example.sunriza26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRdAKnkLN4P_O3ahbHEUz1Z6QPa51ZPU',
    appId: '1:198085957474:web:a26226a8f9d1d0759ffe3b',
    messagingSenderId: '198085957474',
    projectId: 'hauau-dev',
    authDomain: 'hauau-dev.firebaseapp.com',
    storageBucket: 'hauau-dev.firebasestorage.app',
    measurementId: 'G-M3Q0LL2HXB',
  );
}
